version: "3"

services:
  server-app:
    container_name: booklistbackend-container
    restart: always
    image: booklistbackend
    ports:
      - "3000:3000"
    links:
      - mongo:4.4.13
    depends_on:
      - mongo
    volumes:
      - "./backEnd/:/server-app/"
      - "/app/node_modules"
    environment: 
      DB_URL: mongodb://mongo:27017/
      MONGO_PASS: example
      MONGO_USER: root
      MONGO_DB: booklistAuth
      MONGO_PORT: 27017
      PORT: 3000
  

  client-app:
    container_name: booklistfrontend-container
    image: booklistfrontend
    ports:
      - "3001:3001"
    depends_on:
      - server-app
    volumes:
      - "./my-app/:/client-app/"
      - "/app/node_modules"
    environment:
      PORT: 3001
   

  mongo:
    container_name: mongo-container
    image: mongo:4.4.13
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
      - ./dump:/dump
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: bookList